RabeyaMuna__diff__id_308

diff --git a/.github/workflows/github-ci.yaml b/.github/workflows/github-ci.yaml
--- a/.github/workflows/github-ci.yaml
+++ b/.github/workflows/github-ci.yaml
@@ -3,20 +3,7 @@
 
 name: CI
 
-on:
-  push:
-    branches:
-      - main
-    paths-ignore:
-      - '**/*.md'
-      - '**/*.rst'
-  pull_request:
-    branches:
-      - main
-    paths-ignore:
-      - '**/*.md'
-      - '**/*.rst'
-  workflow_dispatch:
+on: push
 
 jobs:
   test_windows:
@@ -26,7 +13,7 @@ jobs:
     - name: Checkout Code
       uses: actions/checkout@v5
       with:
-        submodules: 'recursive'
+        submodules: recursive
     - name: Setup Python (3.11+)
       uses: actions/setup-python@v6
       with:
@@ -53,28 +40,27 @@ jobs:
 
 
   tests:
-    name: "pytest on ${{ matrix.python-version }} (crypto-lib: ${{ matrix.use-crypto-lib }})"
+    name: 'pytest on ${{ matrix.python-version }} (crypto-lib: ${{ matrix.use-crypto-lib
+      }})'
     runs-on: ubuntu-22.04
     strategy:
       matrix:
-        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.14"]
-        use-crypto-lib: ["cryptography"]
+        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
+        use-crypto-lib: [cryptography]
         include:
-          - python-version: "3.9"
-            use-crypto-lib: "pycryptodome"
-          - python-version: "3.9"
-            use-crypto-lib: "none"
+        - python-version: '3.9'
+          use-crypto-lib: pycryptodome
+        - python-version: '3.9'
+          use-crypto-lib: none
     steps:
     - name: Update APT packages
-      run:
-        sudo apt-get update
+      run: sudo apt-get update
     - name: Install APT dependencies
-      run:
-        sudo apt-get install ghostscript jbig2dec poppler-utils
+      run: sudo apt-get install ghostscript jbig2dec poppler-utils
     - name: Checkout Code
       uses: actions/checkout@v5
       with:
-        submodules: 'recursive'
+        submodules: recursive
     - name: Cache Downloaded Files
       id: cache-downloaded-files
       uses: actions/cache@v4
@@ -86,7 +72,7 @@ jobs:
       if: matrix.python-version == '3.9' || matrix.python-version == '3.10'
       with:
         python-version: ${{ matrix.python-version }}
-        cache: 'pip'
+        cache: pip
         cache-dependency-path: '**/requirements/ci.txt'
     - name: Setup Python (3.11+)
       uses: actions/setup-python@v6
@@ -94,7 +80,7 @@ jobs:
       with:
         python-version: ${{ matrix.python-version }}
         allow-prereleases: true
-        cache: 'pip'
+        cache: pip
         cache-dependency-path: '**/requirements/ci-3.11.txt'
     - name: Upgrade pip
       run: |
@@ -139,13 +125,14 @@ jobs:
       run: |
         python -m pytest tests --cov=pypdf --cov-append -n auto -vv -p no:benchmark
       env:
-        COVERAGE_PROCESS_START: 'pyproject.toml'
+        COVERAGE_PROCESS_START: pyproject.toml
     - name: Rename coverage data file
       run: mv .coverage ".coverage.$RANDOM"
     - name: Upload coverage data
       uses: actions/upload-artifact@v5
       with:
-        name: coverage-data.${{ matrix.python-version }}-${{ matrix.use-crypto-lib }}
+        name: coverage-data.${{ matrix.python-version }}-${{ matrix.use-crypto-lib
+          }}
         path: .coverage.*
         if-no-files-found: ignore
         include-hidden-files: true
@@ -157,12 +144,12 @@ jobs:
     - name: Checkout Code
       uses: actions/checkout@v5
       with:
-        submodules: 'recursive'
+        submodules: recursive
     - name: Setup Python 3.11
       uses: actions/setup-python@v6
       with:
-        python-version: "3.11"
-        cache: 'pip'
+        python-version: '3.11'
+        cache: pip
         cache-dependency-path: '**/requirements/ci-3.11.txt'
     - name: Upgrade pip
       run: |
@@ -178,7 +165,7 @@ jobs:
         echo `ruff --version`
         ruff check .
     - name: Test with mypy
-      run : |
+      run: |
         mypy pypdf
     - name: Install docs requirements
       run: |
@@ -201,27 +188,27 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v5
-      - uses: actions/setup-python@v6
-        with:
-          python-version: ${{ env.PYTHON_LATEST }}
+    - uses: actions/checkout@v5
+    - uses: actions/setup-python@v6
+      with:
+        python-version: ${{ env.PYTHON_LATEST }}
 
-      - run: python -m pip install flit check-wheel-contents
-      - run: flit build
-      - run: ls -l dist
+    - run: python -m pip install flit check-wheel-contents
+    - run: flit build
+    - run: ls -l dist
 
-      - name: Test CHANGELOG.md present in sdist
-        run: tar -tzf dist/*.tar.gz | grep -q 'CHANGELOG.md'
+    - name: Test CHANGELOG.md present in sdist
+      run: tar -tzf dist/*.tar.gz | grep -q 'CHANGELOG.md'
 
-      - name: Test of bdist
-        run: check-wheel-contents dist/*.whl
+    - name: Test of bdist
+      run: check-wheel-contents dist/*.whl
 
-      - name: Test installing package
-        run: python -m pip install .
+    - name: Test installing package
+      run: python -m pip install .
 
-      - name: Test running installed package
-        working-directory: /tmp
-        run: python -c "import pypdf;print(pypdf.__version__)"
+    - name: Test running installed package
+      working-directory: /tmp
+      run: python -c "import pypdf;print(pypdf.__version__)"
 
   coverage:
     name: Combine & check coverage.
@@ -229,35 +216,35 @@ jobs:
     needs: tests
 
     steps:
-      - uses: actions/checkout@v5
-      - uses: actions/setup-python@v6
-        with:
+    - uses: actions/checkout@v5
+    - uses: actions/setup-python@v6
+      with:
           # Use the latest Python, so it understands all syntax.
-          python-version: ${{ env.PYTHON_LATEST }}
+        python-version: ${{ env.PYTHON_LATEST }}
 
-      - run: python -m pip install --upgrade coverage[toml]
+    - run: python -m pip install --upgrade coverage[toml]
 
-      - uses: actions/download-artifact@v6
-        with:
-          pattern: coverage-data*
-          merge-multiple: true
+    - uses: actions/download-artifact@v6
+      with:
+        pattern: coverage-data*
+        merge-multiple: true
 
-      - name: Check Number of Downloaded Files
-        run: |
-          downloaded_files_count=$(find \.coverage* -type f | wc -l)
-          if [ $downloaded_files_count -eq 8 ]; then
-            echo "The expected number of files (8) were downloaded."
-          else
-            echo "ERROR: Expected 8 files, but found $downloaded_files_count files."
-            exit 1
-          fi
+    - name: Check Number of Downloaded Files
+      run: |
+        downloaded_files_count=$(find \.coverage* -type f | wc -l)
+        if [ $downloaded_files_count -eq 8 ]; then
+          echo "The expected number of files (8) were downloaded."
+        else
+          echo "ERROR: Expected 8 files, but found $downloaded_files_count files."
+          exit 1
+        fi
 
-      - name: Combine coverage & create xml report
-        run: |
-          python -m coverage combine
-          python -m coverage xml
-      - name: Upload Coverage to Codecov
-        uses: codecov/codecov-action@v5
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }}
-          files: ./coverage.xml
+    - name: Combine coverage & create xml report
+      run: |
+        python -m coverage combine
+        python -m coverage xml
+    - name: Upload Coverage to Codecov
+      uses: codecov/codecov-action@v5
+      with:
+        token: ${{ secrets.CODECOV_TOKEN }}
+        files: ./coverage.xml
